### ISSUE TITLE
Doesn't work on March 31st

### ISSUE THREAD

**Issue by dizzythinks** [monk-ee/NHDH#7]
Best bug ever?

> > > from datetime import datetime
> > > from dateutil import parser
> > > files = 'XXXXXXXXXXX-aws-billing-detailed-line-items-with-resources-and-tags-2014-02.csv'
> > > datetime.now()
> > > datetime.datetime(2014, 3, 31, 12, 24, 19, 899074)
> > > parser.parse('-'.join(files.split('.')[0].split('-')[-2:])).strftime('%B %Y')
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/usr/local/lib/python2.7/dist-packages/dateutil/parser.py", line 720, in parse
> > >     return DEFAULTPARSER.parse(timestr, **kwargs)
> > >   File "/usr/local/lib/python2.7/dist-packages/dateutil/parser.py", line 317, in parse
> > >     ret = default.replace(**repl)
> > > ValueError: day is out of range for month

Set the system clock to April 1st... works again!

> > > datetime.now()
> > > datetime.datetime(2014, 4, 1, 12, 24, 4, 545817)
> > > parser.parse('-'.join(files.split('.')[0].split('-')[-2:])).strftime('%B %Y')
> > > 'February 2014'

Looks to be some sort of bug in the way dateutil parser works that effects February but only on March 31st o_0

Investigating a fix now

**Comment by monk-ee** [comment]
Ha wow

**Comment by dizzythinks** [comment]
Actually, we can close this, its a bug in a bit I did for work specific view hah! Still.. good to know right?
